const foodData = [
  { id: '1', name: 'Sarmale', price: '£10', description: 'Traditional Romanian cabbage rolls filled with minced meat and rice. Mustard and Bread included', country: 'Romania', category: 'Speciality' },
  { id: '2', name: 'Tochitură', price: '£8', description: 'A hearty Romanian stew made with pork, sausages, and polenta.', country: 'Romania', category: 'Speciality' },
  { id: '3', name: 'Mici', price: '£7', description: 'Grilled sausages made from a mix of beef, lamb, and pork.', country: 'Romania', category: 'Speciality' },
  { id: '4', name: 'Ciorbă de burtă', price: '£6', description: 'Tripe soup with garlic, sour cream, and vinegar.', country: 'Romania', category: 'Ciorbă/Soup' },
  { id: '5', name: 'Ciorbă de fasole', price: '£5', description: 'Bean soup with smoked meat and vegetables.', country: 'Romania', category: 'Ciorbă/Soup' },
  { id: '6', name: 'Ciorbă de perișoare', price: '£5', description: 'Meatball soup with vegetables and sour cream.', country: 'Romania', category: 'Ciorbă/Soup' },
  { id: '7', name: 'Pork steak', price: '£5', description: 'Juicy pork steak served with mashed potatoes.', country: 'Romania', category: 'Pork' },
  { id: '8', name: 'Pork schnitzel', price: '£5', description: 'Breaded and fried pork cutlet served with fries.', country: 'Romania', category: 'Pork' },
  { id: '9', name: 'Spicy pork pan', price: '£5', description: 'Spicy pork stir-fry with vegetables and rice.', country: 'Romania', category: 'Pork' },
  { id: '10', name: 'Papanasi', price: '£6', description: 'Traditional pastry filled with cheese, apples, pumpkin, or cherries.', country: 'Romania', category: 'Deserts' },
  { id: '11', name: 'Cozonac', price: '£5', description: 'Chocolate sponge cake layered with cocoa syrup and chocolate buttercream.', country: 'Romania', category: 'Deserts' },
  { id: '12', name: 'Clătite', price: '£5', description: 'Thin Romanian crêpes filled with jam, chocolate, or sweet cheese.', country: 'Romania', category: 'Deserts' },
  { id: '110', name: 'Colivă', price: '£5', description: 'Death Cake - A traditional Romanian dessert  made from sweetened boiled wheat, flavored with vanilla, sugar, and rum, then topped with powdered sugar and walnuts.', country: 'Romania', category: 'Deserts' },
  { id: '13', name: 'Țuică', price: '£6', description: 'A traditional Romanian plum brandy, smooth and bold.', country: 'Romania', category: 'Beverages' },
  { id: '14', name: 'Palincă', price: '£5', description: 'Premium fruit brandy with a rich, refined taste.', country: 'Romania', category: 'Beverages' },
  { id: '15', name: 'Romanian Beer', price: '£5', description: 'Ursus Or Timișoreana.', country: 'Romania', category: 'Beverages' },
  { id: '16', name: 'Romanian Wine', price: '£5', description: 'Red or White.', country: 'Romania', category: 'Beverages' },
  { id: '17', name: 'Napoletana', price: '£12', description: 'Traditional Neapolitan pizza with tomatoes and mozzarella.', country: 'Italy', category: 'Pizza' },
  { id: '18', name: 'Margherita', price: '£14', description: 'Classic pizza with tomato, mozzarella, and basil.', country: 'Italy', category: 'Pizza' },
  { id: '19', name: 'Siciliana', price: '£14', description: 'Sicilian-style pizza with anchovies and olives.', country: 'Italy', category: 'Pizza' },
  { id: '20', name: 'Quattro Formaggi', price: '£14', description: 'Pizza topped with four types of cheese.', country: 'Italy', category: 'Pizza' },
  { id: '21', name: 'Capricciosa', price: '£14', description: 'Pizza with ham, mushrooms, artichokes, and olives.', country: 'Italy', category: 'Pizza' },
  { id: '22', name: 'Build your own pizza', price: '£14', description: 'Customize your pizza with your favorite toppings.', country: 'Italy', category: 'Pizza' },
  { id: '23', name: 'Spaghetti Carbonara', price: '£10', description: 'Pasta with eggs, cheese, pancetta, and black pepper.', country: 'Italy', category: 'Pasta' },
  { id: '24', name: 'Fettuccine Alfredo', price: '£12', description: 'Creamy pasta with butter and Parmesan cheese.', country: 'Italy', category: 'Pasta' },
  { id: '25', name: 'Tagliatelle al Ragù (Bolognese)', price: '£12', description: 'Pasta with a rich meat-based sauce.', country: 'Italy', category: 'Pasta' },
  { id: '26', name: 'Spaghetti allo Scoglio', price: '£12', description: 'Seafood pasta with a tomato-based sauce.', country: 'Italy', category: 'Pasta' },
  { id: '27', name: 'Pasta Quattro Formaggi', price: '£12', description: 'Pasta with a creamy four-cheese sauce.', country: 'Italy', category: 'Pasta' },
  { id: '28', name: 'Tiramisu', price: '£10', description: 'Layers of coffee-soaked ladyfingers, mascarpone cream, and cocoa powder.', country: 'Italy', category: 'Italian Deserts' },
  { id: '29', name: 'Panna Cotta', price: '£12', description: 'Silky vanilla cream dessert, often topped with fruit sauce or caramel.', country: 'Italy', category: 'Italian Deserts' },
  { id: '30', name: 'Torta Caprese', price: '£12', description: 'Flourless chocolate and almond cake, rich and fudgy.', country: 'Italy', category: 'Italian Deserts' },
  { id: '31', name: 'Biscotti', price: '£12', description: 'Crunchy almond cookies, perfect for dipping in coffee or Vin Santo wine.', country: 'Italy', category: 'Italian Deserts' },
  { id: '32', name: 'Espresso', price: '£10', description: 'A small, strong shot of coffee, brewed to perfection with rich, bold flavor.', country: 'Italy', category: 'Beverages' },
  { id: '33', name: 'Cappuccino', price: '£12', description: 'A smooth, velvety espresso topped with frothed milk and a dusting of cocoa.', country: 'Italy', category: 'Beverages' },
  { id: '34', name: 'Latte', price: '£12', description: 'A delicate combination of espresso and steamed milk, creating a smooth and creamy coffee.', country: 'Italy', category: 'Beverages' },
  { id: '35', name: 'Macchiato', price: '£12', description: 'Espresso "stained" with a touch of steamed milk.', country: 'Italy', category: 'Beverages' },
  { id: '36', name: 'Peroni', price: '£12', description: 'A premium Italian lager with a crisp, clean taste and a subtle hop bitterness.', country: 'Italy', category: 'Beverages' },
  { id: '37', name: 'Moussaka', price: '£12', description: 'Layered dish with eggplant, minced meat, and béchamel sauce.', country: 'Greece', category: 'Greek Specials' },
{ id: '38', name: 'Souvlaki', price: '£12', description: 'Layered dish with eggplant, minced meat, and béchamel sauce.', country: 'Greece', category: 'Greek Specials' },
{ id: '39', name: 'Gyros', price: '£12', description: 'Pita bread filled with grilled meat, vegetables, and sauce.', country: 'Greece', category: 'Greek Specials' },
{ id: '40', name: 'Spanakopita', price: '£12', description: 'Spinach and feta cheese pie wrapped in phyllo dough.', country: 'Greece', category: 'Greek Specials' },
{ id: '41', name: 'Baklava', price: '£12', description: 'Layered phyllo pastry filled with nuts and drenched in honey syrup.', country: 'Greece', category: 'Greek Deserts' },
{ id: '42', name: 'Galaktoboureko', price: '£12', description: 'Creamy custard baked in phyllo pastry and soaked in syrup.', country: 'Greece', category: 'Greek Deserts' },
{ id: '43', name: 'Halva', price: '£12', description: 'A refreshing blend of Greek yogurt, cucumber, garlic, dill, and a hint of lemon juice.', country: 'Greece', category: 'Greek Deserts' },
{ id: '44', name: 'Tzatziki', price: '£12', description: 'A semolina-based sweet treat with nuts, honey, and cinnamon.', country: 'Greece', category: 'Greek sauces/dips' },
{ id: '45', name: 'Htipiti ', price: '£12', description: 'A creamy, spicy feta dip made with roasted red peppers, olive oil, and herbs.', country: 'Greece', category: 'Greek sauces/dips' },
{ id: '46', name: 'Skordalia', price: '£12', description: 'A garlicky, velvety dip made with mashed potatoes, olive oil, vinegar, and garlic.', country: 'Greece', category: 'Greek sauces/dips' },
{ id: '47', name: 'Avgolemono ', price: '£12', description: 'A rich, velvety sauce made from eggs, lemon juice, and broth.', country: 'Greece', category: 'Greek sauces/dips' },
{ id: '48', name: 'Peking Duck', price: '£12', description: 'Crispy roasted duck served with pancakes and hoisin sauce.', country: 'China', category: 'Chinese Specials' },
{ id: '49', name: 'Kung Pao Chicken', price: '£12', description: 'Spicy stir-fried chicken with peanuts and vegetables.', country: 'China', category: 'Chinese Specials' },
{ id: '50', name: 'Sweet and Sour Pork', price: '£12', description: 'Crispy pork in a sweet and tangy sauce.', country: 'China', category: 'Chinese Specials' },
{ id: '51', name: 'Dumplings', price: '£12', description: 'Steamed or fried dumplings filled with meat or vegetables.', country: 'China', category: 'Chinese Specials' },
{ id: '52', name: 'Fried Rice', price: '£12', description: 'Stir-fried rice with eggs and vegetables', country: 'China', category: 'Chinese Specials' },
{ id: '53', name: 'Tangyuan', price: '£12', description: 'Glutinous rice balls filled with sweet sesame or peanut paste, served in warm syrup.', country: 'China', category: 'Chinese Deserts' },
{ id: '54', name: 'Mooncakes ', price: '£12', description: 'Traditional round pastries filled with red bean paste, lotus seed paste, or salted egg yolk.', country: 'China', category: 'Chinese Deserts' },
{ id: '55', name: 'Steamed Sponge Cake (Ma Lai Gao)', price: '£12', description: 'Soft and fluffy Cantonese-style sponge cake with a light caramel flavor.', country: 'China', category: 'Chinese Deserts' },
{ id: '56', name: 'Pineapple Buns (Bo Lo Bao)', price: '£12', description: 'Soft, sweet buns with a crumbly, golden sugary crust.', country: 'China', category: 'Chinese Deserts' },
{ id: '57', name: 'Tacos', price: '£12', description: 'Soft or crispy tortillas filled with meats like al pastor, carnitas, or barbacoa, topped with onions, cilantro, and salsa.', country: 'Mexico', category: 'Mexican Specials' },
{ id: '58', name: 'Tamales', price: '£12', description: 'Steamed corn dough parcels filled with shredded chicken, pork, or sweet options, wrapped in corn husks.', country: 'Mexico', category: 'Mexican Specials' },
{ id: '59', name: 'Tamales', price: '£12', description: 'Steamed corn dough parcels filled with shredded chicken, pork, or sweet options, wrapped in corn husks.', country: 'Mexico', category: 'Mexican Specials' },
{ id: '60', name: 'Enchiladas', price: '£12', description: 'Rolled corn tortillas filled with meat or cheese, topped with red, green, or mole sauce.', country: 'Mexico', category: 'Mexican Specials' },
{ id: '61', name: 'Birria', price: '£12', description: 'Slow-cooked beef or goat stew infused with spices and dried chilies, served with tortillas and broth for dipping.', country: 'Mexico', category: 'Mexican Specials' },
{ id: '62', name: 'Chiles en Nogada', price: '£12', description: 'Roasted poblano peppers stuffed with meat, fruit, and spices, topped with walnut sauce and pomegranate seeds.', country: 'Mexico', category: 'Mexican Specials' },
{ id: '63', name: 'Churros', price: '£12', description: 'Fried dough pastries coated in cinnamon sugar, often served with chocolate or caramel sauce.', country: 'Mexico', category: 'Mexican Desserts' },
{ id: '64', name: 'Tres Leches Cake', price: '£12', description: 'Moist sponge cake soaked in three kinds of milk, topped with whipped cream.', country: 'Mexico', category: 'Mexican Desserts' },
{ id: '65', name: 'Flan', price: '£12', description: 'Creamy caramel custard with a smooth, velvety texture.', country: 'Mexico', category: 'Mexican Desserts' },
{ id: '66', name: 'Pan de Muerto', price: '£12', description: 'Sweet, soft bread traditionally enjoyed during Día de los Muertos, flavored with orange zest and anise.', country: 'Mexico', category: 'Mexican Desserts' },
{ id: '67', name: 'Arroz con Leche', price: '£12', description: 'Mexican-style rice pudding cooked with cinnamon, vanilla, and sweetened milk.', country: 'Mexico', category: 'Mexican Desserts' },
{ id: '68', name: 'Margarita', price: '£12', description: 'A refreshing blend of tequila, lime juice, and orange liqueur, served on the rocks or blended with a salted rim', country: 'Mexico', category: 'Mexican Beverages ' },
{ id: '69', name: 'Tequila', price: '£12', description: 'Choose from Don Julio Reposado, Anejo or Blanco  Tequila', country: 'Mexico', category: 'Mexican Beverages ' },
{ id: '70', name: 'Agua Fresca', price: '£12', description: 'A light, refreshing beverage made from a variety of fruits like watermelon, hibiscus, or tamarind, mixed with water and a touch of sugar', country: 'Mexico', category: 'Mexican Beverages ' },
{ id: '71', name: 'Sushi', price: '£12', description: 'Vinegared rice paired with fresh seafood, vegetables, or egg, served as rolls or nigiri.', country: 'Japan', category: 'Japanese Specials' },
{ id: '72', name: 'Ramen', price: '£12', description: 'Japanese noodle soup with rich broth, noodles, meat, and toppings like eggs and seaweed.', country: 'Japan', category: 'Japanese Specials' },
{ id: '73', name: 'Tempura', price: '£12', description: 'Crispy battered and deep-fried seafood or vegetables, served with dipping sauce.', country: 'Japan', category: 'Japanese Specials' },
{ id: '74', name: 'Tonkatsu', price: '£12', description: 'Breaded and deep-fried pork cutlet served with shredded cabbage and tonkatsu sauce.', country: 'Japan', category: 'Japanese Specials' },
{ id: '75', name: 'Okonomiyaki', price: '£12', description: 'Savory Japanese pancake made with cabbage, batter, and various toppings.', country: 'Japan', category: 'Japanese Specials' },
{ id: '76', name: 'Mochi', price: '£12', description: 'Chewy rice cakes filled with sweet red bean paste or ice cream', country: 'Japan', category: 'Japanese Desserts' },
{ id: '77', name: 'Dorayaki', price: '£12', description: 'Fluffy pancake-like pastries filled with sweet red bean paste.', country: 'Japan', category: 'Japanese Desserts' },
{ id: '78', name: 'Matcha Ice Cream', price: '£12', description: 'Green tea-flavored ice cream with a slightly bitter and creamy taste.', country: 'Japan', category: 'Japanese Desserts' },
{ id: '79', name: 'Taiyaki', price: '£12', description: 'Fish-shaped pastry filled with sweet fillings like red bean, custard, or chocolate.', country: 'Japan', category: 'Japanese Desserts' },
{ id: '80', name: 'Yokan', price: '£12', description: 'Jelly-like sweet made from red bean paste, agar, and sugar.', country: 'Japan', category: 'Japanese Desserts' },
{ id: '81', name: 'Sake', price: '£12', description: 'Rice wine with a delicate balance of sweetness and umami', country: 'Japan', category: 'Japanese Beverages' },
{ id: '82', name: 'Matcha Latte', price: '£12', description: 'A smooth and creamy blend of finely ground green tea and steamed milk', country: 'Japan', category: 'Japanese Beverages' },
{ id: '83', name: 'Ramune', price: '£12', description: 'A fun and fizzy Japanese soda with a signature glass marble seal. Available in a variety of fruity flavors', country: 'Japan', category: 'Japanese Beverages' },
{ id: '84', name: 'Hojicha', price: '£12', description: 'A roasted green tea with a warm, nutty aroma and a smooth, toasty flavor', country: 'Japan', category: 'Japanese Beverages' },
{ id: '85', name: 'Burger', price: '£12', description: ' Classic American sandwich with a beef patty, lettuce, tomato, cheese, condiments. Served with a side of crispy fries.', country: 'USA', category: 'American Specials' },
{ id: '86', name: 'BBQ Ribs', price: '£12', description: 'Slow-cooked pork ribs coated in smoky barbecue sauce.', country: 'USA', category: 'American Specials' },
{ id: '87', name: 'Fried Chicken', price: '£12', description: 'Crispy, seasoned deep-fried chicken pieces.', country: 'USA', category: 'American Specials' },
{ id: '88', name: 'Mac and Cheese', price: '£12', description: 'Creamy pasta dish made with melted cheese sauce and baked to perfection.', country: 'USA', category: 'American Specials' },
{ id: '89', name: 'Clam Chowder', price: '£12', description: 'Creamy soup with clams, potatoes, and vegetables.', country: 'USA', category: 'American Specials' },

{ id: '91', name: 'Apple Pie', price: '£12', description: 'Classic American pie with spiced apples in a flaky crust.', country: 'USA', category: 'American Desserts' },
{ id: '92', name: 'Cheesecake', price: '£12', description: 'Rich and creamy dessert with a graham cracker crust, topped with fruit or chocolate', country: 'USA', category: 'American Desserts' },
{ id: '93', name: 'Brownies', price: '£12', description: 'Fudgy or cakey chocolate squares, sometimes with nuts or caramel.', country: 'USA', category: 'American Desserts' },
{ id: '94', name: 'Pumpkin Pie', price: '£12', description: 'Spiced pumpkin custard pie, popular during Thanksgiving.', country: 'USA', category: 'American Desserts' },
{ id: '95', name: 'Ice Cream Sundae', price: '£12', description: 'Vanilla ice cream topped with hot fudge, whipped cream, nuts, and a cherry.', country: 'USA', category: 'American Desserts' },
{ id: '96', name: 'Ice Tea', price: '£12', description: 'Served chilled with a wedge of lemon and a touch of sweetness.', country: 'USA', category: 'American Beverages' },
{ id: '97', name: 'Lemonade', price: '£12', description: 'Freshly squeezed lemon juice, water, and sugar, served ice-cold.', country: 'USA', category: 'American Beverages' },
{ id: '98', name: 'Milkshake', price: '£12', description: 'A thick, creamy blend of premium ice cream and milk, topped with whipped cream and a cherry. Available in classic flavors like chocolate, vanilla, and strawberry.', country: 'USA', category: 'American Beverages' },
{ id: '99', name: 'Ranch Dressing', price: '£12', description: 'A creamy, tangy blend of buttermilk, garlic, and herbs.', country: 'USA', category: 'American Sauces/Dips' },
{ id: '99', name: 'BBQ Sauce', price: '£12', description: 'A smoky, sweet, and tangy sauce with a rich depth of flavor.', country: 'USA', category: 'American Sauces/Dips' },
{ id: '100', name: 'Mustard', price: '£12', description: 'Mustaaaaaaaaaard', country: 'USA', category: 'American Sauces/Dips' },
{ id: '101', name: 'Ketchup', price: '£12', description: 'Ketchup', country: 'USA', category: 'American Sauces/Dips' },
{ id: '101', name: 'Mayonnaise', price: '£12', description: 'Mayo', country: 'USA', category: 'American Sauces/Dips' },
{ id: '101', name: 'Garlic Mayonnaise', price: '£12', description: 'Garlic Mayo', country: 'USA', category: 'American Sauces/Dips' },
{ id: '102', name: 'English Breakfast', price: '£12', description: 'A hearty and satisfying classic, featuring crispy bacon, tender sausages, eggs cooked to your liking, grilled tomatoes, baked beans, and golden, buttered toast', country: 'Worldwide', category: 'Specials' },
{ id: '103', name: 'Sunday Roast', price: '£12', description: ' Roasted meat, roasted potatoes or mashed potatoes, and accompaniments such as Yorkshire pudding, stuffing or gravy,', country: 'Worldwide', category: 'Specials' },
{ id: '104', name: 'Chicken Tikka', price: '£12', description: ' Tender chunks of marinated chicken, spiced with aromatic Indian herbs and yogurt, then grilled to perfection', country: 'Worldwide', category: 'Specials' },
{ id: '105', name: 'Shawarma', price: '£12', description: ' Thinly sliced, seasoned lamb, chicken, or beef, slow-cooked on a vertical rotisserie and served in a warm pita or flatbread. Accompanied by fresh vegetables, tahini sauce, and a drizzle of garlic sauce', country: 'Worldwide', category: 'Specials' },
{ id: '106', name: 'Orange Juice', price: '£12', description: ' Freshly squeezed', country: 'Worldwide', category: 'Drinks' },
{ id: '107', name: 'Apple Juice', price: '£12', description: ' Crisp, refreshing, and naturally sweet', country: 'Worldwide', category: 'Drinks' },
{ id: '108', name: 'Tropical Juice', price: '£12', description: ' Mango, pineapple, and passionfruit', country: 'Worldwide', category: 'Drinks' },





  
];

export { foodData };